# REQ: SWR-024, SWR-050; RISK: RISK-010, RISK-012; SEC: SC-012; TEST: TC-023
[Unit]
Requires=monitor-avahi-pin.service
After=monitor-avahi-pin.service

[Service]
ExecStart=
ExecStart=/usr/sbin/avahi-daemon -s -f /data/config/avahi-daemon.conf
